[project]
name = "backend"
version = "0.1.0"
description = "Uses FastAPI to send response to frontend"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.8",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.40.0",
]
